"on":
  workflow_dispatch:
    inputs:
      environment_id:
        description: Environment ID
        required: true
        type: number
      pr_number:
        description: Pull request number
        required: true
        type: number
      repo_name:
        description: Repository name
        required: true
        type: string
      repo_owner:
        description: Repository owner
        required: true
        type: string
name: Porter Preview Environment
jobs:
  porter-delete-preview:
    runs-on: ubuntu-latest
    steps:
    - name: Delete Porter preview env
      timeout-minutes: 30
      uses: porter-dev/porter-delete-preview-action@v0.2.0
      with:
        cluster: "34"
        environment_id: ${{ github.event.inputs.environment_id }}
        host: https://dashboard.dev.getporter.dev
        pr_number: ${{ github.event.inputs.pr_number }}
        project: "3"
        repo_name: porter-docs
        repo_owner: ${{ github.repository_owner }}
        token: ${{ secrets.PORTER_TOKEN_3 }}
